apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # Selects pods with the "my-app" label
  ports:
    - protocol: TCP
      port: 80  # Port that the service exposes
      targetPort: 80  # Port to forward traffic to on the pods
  type: ClusterIP  # Internal service (default)
